### ISSUE TITLE
wieghts problems

### ISSUE THREAD

**Issue by HamidFsian** [potpov/alveolar_canal#3]
Hi,
I am having trouble testing the model **PosPadUNet3D** using a similar conf.yaml that you provided.

```
title: alveolar_canal_finetuning
project_dir: 'results'
seed: 47

experiment:
  name: Segmentation

data_loader:
  dataset: IAN_Maxillo_dataset\dataset_for_public
  training_set: null
  preprocessing: configs/preprocessing.yaml
  augmentations: configs/augmentations.yaml
  background_suppression: 0
  batch_size: 1
  labels:
    BACKGROUND: 0
    INSIDE: 1
  mean: 0.08435
  num_workers: 4
  patch_shape:
  - 80
  - 80
  - 80
  resize_shape:
  - 168
  - 280
  - 360
  sampler_type: grid
  grid_overlap: 0
  std: 0.17885
  volumes_max: 2100
  volumes_min: 0
  weights:
  - 0.000703
  - 0.999

model:
  name: PosPadUNet3D

loss:
  name: Jaccard

lr_scheduler:
  name: Plateau

optimizer:
  learning_rate: 0.1
  name: Adam

trainer:
  reload: True
  checkpoint: checkpoints\last-seg-pretraining.pth
  do_train: False
  do_test: True
  do_inference: False
  epochs: 100

```
But still end with theses metrics : 

```
wandb: Run summary:
wandb:     Epoch 29
wandb: Test/Dice 0.0
wandb:  Test/IoU 0.0
wandb: Test/Loss 1.0
```
PS : Sorry, I created a new issue here. Because I could not create one on AImagelab-zip repository.

Can you please help me.

Regards,
Hamid FSIAN
